<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class KretaSetupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('kreta_setups')->delete();
        
        \DB::table('kreta_setups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'সততা ট্রেডিং',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:20:36',
                'updated_at' => '2023-12-21 06:20:36',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'মুক্তা এন্টারপ্রাইজ',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:21:59',
                'updated_at' => '2023-12-21 06:21:59',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'শাহীন ভাই',
                'address' => 'পাবনা',
                'mobile' => '00',
                'area' => 'পাবনা',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:24:57',
                'updated_at' => '2023-12-21 06:24:57',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'মদীনা ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:27:12',
                'updated_at' => '2023-12-21 06:27:12',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'আল্লারদান বানিজ্যালয়',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:28:41',
                'updated_at' => '2023-12-21 06:28:41',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ফৌজিয়া এন্টারপ্রাইজ',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:29:41',
                'updated_at' => '2023-12-21 06:29:41',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'হাজী জালাল আহম্মদ',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:30:09',
                'updated_at' => '2023-12-21 06:30:09',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ভাই ভাই স্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:31:17',
                'updated_at' => '2023-12-21 06:31:17',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'করিম ডিপার্টমেন্টাল স্টোর',
                'address' => 'ফেনী রেলগেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:33:17',
                'updated_at' => '2023-12-21 06:40:36',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'নাজিম ষ্টোর',
                'address' => 'মুক্তাবাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:34:12',
                'updated_at' => '2023-12-21 06:34:12',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'নগর বাজার',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:34:36',
                'updated_at' => '2023-12-21 06:34:36',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'কালাম ভাই',
                'address' => 'বারাহিপুর রেলগেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:35:31',
                'updated_at' => '2023-12-21 06:37:11',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'দিলীপ সাহা',
                'address' => 'ফাজিলপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:37:42',
                'updated_at' => '2023-12-21 06:37:42',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'জাহাঙ্গির মিয়া',
                'address' => 'ফেনী রেলগেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:39:53',
                'updated_at' => '2023-12-21 06:39:53',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'মায়ের দোয়া বানিজ্যালয়',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:42:30',
                'updated_at' => '2023-12-21 06:42:30',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'জাহাঙ্গীর ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:43:40',
                'updated_at' => '2023-12-21 06:43:40',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'ইউনুস ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:44:12',
                'updated_at' => '2023-12-21 06:44:12',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'দিনেশ মজুমদার',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:45:05',
                'updated_at' => '2023-12-21 06:45:05',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'মানিক ভাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:46:24',
                'updated_at' => '2023-12-21 06:46:24',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'তাকওয়া এন্টারপ্রাইজ',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:47:08',
                'updated_at' => '2023-12-21 06:47:08',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'পর্ব ট্রেডিং',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:48:41',
                'updated_at' => '2023-12-21 06:48:41',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'বাগদাদ ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:49:22',
                'updated_at' => '2023-12-21 06:49:22',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'পলাশ ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:50:31',
                'updated_at' => '2023-12-21 06:50:31',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ইশরাক ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:51:19',
                'updated_at' => '2023-12-21 06:51:19',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'কামাল এন্ড ব্রাদার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:51:56',
                'updated_at' => '2023-12-21 06:51:56',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'রাজীব সাহা',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:52:29',
                'updated_at' => '2023-12-21 06:52:29',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'হক ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 06:53:35',
                'updated_at' => '2023-12-21 06:53:35',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'আসবব  ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:07:17',
                'updated_at' => '2023-12-21 07:07:17',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'শহিদ ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:07:59',
                'updated_at' => '2023-12-21 07:07:59',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ওসমান গনি',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:08:48',
                'updated_at' => '2023-12-21 07:08:48',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'জয়নাল ব্রাদার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:09:13',
                'updated_at' => '2023-12-21 07:09:13',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'সাহাব উদ্দিন',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:09:34',
                'updated_at' => '2023-12-21 07:09:34',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'মোল্লা বানিজ্যালয়',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:10:06',
                'updated_at' => '2023-12-21 07:10:06',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'নিউ ফেনী ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:10:32',
                'updated_at' => '2023-12-21 07:10:32',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'এস বি ট্রেডার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:10:59',
                'updated_at' => '2023-12-21 07:10:59',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ইব্রাহীম এন্ড ব্রাদার্স',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:11:24',
                'updated_at' => '2023-12-21 07:11:24',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'শাহীন ভাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:11:56',
                'updated_at' => '2023-12-21 07:11:56',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'আবুল হাশেম চৌধুরী',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:13:13',
                'updated_at' => '2023-12-21 07:13:13',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'নিতীহ সাহা',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:13:55',
                'updated_at' => '2023-12-21 07:13:55',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'জাহাঙ্গীর ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:14:38',
                'updated_at' => '2023-12-21 07:14:38',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'এয়াকুব ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:15:45',
                'updated_at' => '2023-12-21 07:15:45',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'সোহেল এন্টারপ্রাইজ',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:16:40',
                'updated_at' => '2023-12-21 07:16:40',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'হাজী কালা মিয়া',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:17:13',
                'updated_at' => '2023-12-21 07:17:13',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'কাশেম ভাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:17:42',
                'updated_at' => '2023-12-21 07:17:42',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'রহীম ভূঁইয়া',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:19:26',
                'updated_at' => '2023-12-21 07:19:26',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'সাইদুল হক',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:20:27',
                'updated_at' => '2023-12-21 07:20:27',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'শামছু ভাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:21:43',
                'updated_at' => '2023-12-21 07:21:43',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'আব্দুল হাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:22:19',
                'updated_at' => '2023-12-21 07:22:19',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'গফুর মিয়া',
                'address' => 'নারিকেল পট্টি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:22:53',
                'updated_at' => '2023-12-21 07:22:53',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'হুমায়ন ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:23:24',
                'updated_at' => '2023-12-21 07:23:24',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'মক্কা ষ্টোর',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:23:50',
                'updated_at' => '2023-12-21 07:23:50',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'সুকোমাল পাল',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:25:09',
                'updated_at' => '2023-12-21 07:25:09',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'গার্ডেন হোটেল অ্যান্ড রেস্টুরেন্ট',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:26:11',
                'updated_at' => '2023-12-21 07:26:11',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'বাঙ্গালিয়ান রেস্টুরেন্ট',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:27:32',
                'updated_at' => '2023-12-21 07:27:32',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'দ্যা ভোজন কোম্পানী',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:28:06',
                'updated_at' => '2023-12-21 07:28:06',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'জামাল মিয়া',
                'address' => 'ফেনী রেলগেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:28:38',
                'updated_at' => '2023-12-21 07:28:38',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'লিটন মিয়া',
                'address' => 'ফেনী রেলগেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:28:59',
                'updated_at' => '2023-12-21 07:28:59',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'সফিকুর রহমান',
                'address' => 'হকার্স মার্কেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:29:36',
                'updated_at' => '2023-12-21 07:29:36',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'হান্নান ভাই',
                'address' => 'হকার্স মার্কেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:29:59',
                'updated_at' => '2023-12-21 07:29:59',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'মজুমদার ষ্টোর',
                'address' => 'হকার্স মার্কেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:30:23',
                'updated_at' => '2023-12-21 07:30:23',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'মনির ভাই',
                'address' => 'হকার্স মার্কেট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:31:41',
                'updated_at' => '2023-12-21 07:31:41',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'সাহাব উদ্দিন',
                'address' => 'কুমিল্লা বাস স্ট্যান্ড',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:32:23',
                'updated_at' => '2023-12-21 07:32:23',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'অরুন ভাই',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:32:44',
                'updated_at' => '2023-12-21 07:32:44',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'হান্নান ভাই',
                'address' => 'আল কেমী',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:33:20',
                'updated_at' => '2023-12-21 07:33:20',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'জেরিন ষ্টোর',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:34:51',
                'updated_at' => '2023-12-21 07:34:51',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'ফারুক ভাই',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:35:14',
                'updated_at' => '2023-12-21 07:35:14',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'ওহাব ষ্টোর',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:35:47',
                'updated_at' => '2023-12-21 07:35:47',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'মীর ষ্টোর',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:36:19',
                'updated_at' => '2023-12-21 07:36:19',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'কামাল ভাই',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:36:43',
                'updated_at' => '2023-12-21 07:36:43',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'রহমান ব্রাদার্স',
                'address' => 'মহিপাল',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:37:16',
                'updated_at' => '2023-12-21 07:37:16',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'আলী হোসেন',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:38:08',
                'updated_at' => '2023-12-21 07:38:08',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'রাসেল মিয়া',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:38:33',
                'updated_at' => '2023-12-21 07:38:33',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'শরিয়ত ভাই',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:39:10',
                'updated_at' => '2023-12-21 07:39:10',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'লাভু মিয়া',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:39:31',
                'updated_at' => '2023-12-21 07:39:31',
            ),
            74 => 
            array (
                'id' => 75,
            'name' => 'আবুল খায়ের (ভান্ডারী)',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:40:12',
                'updated_at' => '2023-12-21 07:40:12',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'বাবুল মিয়া',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:40:44',
                'updated_at' => '2023-12-21 07:40:44',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'গিয়াস ভাই',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:41:53',
                'updated_at' => '2023-12-21 07:41:53',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'রহিম ভাই',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:42:17',
                'updated_at' => '2023-12-21 07:42:17',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'রনজিত দা',
                'address' => 'পাঁচগাছিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:44:08',
                'updated_at' => '2023-12-21 07:44:08',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'মিলন ষ্টোর',
                'address' => 'পুলিশ কোয়ার্টার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:45:20',
                'updated_at' => '2023-12-21 07:45:20',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'সানাউল্লাহ ট্রেডার্স',
                'address' => 'পুলিশ কোয়ার্টার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:45:48',
                'updated_at' => '2023-12-21 07:45:48',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'নেজাম ভাই',
                'address' => 'শাহিন একাডেমী',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:47:02',
                'updated_at' => '2023-12-21 07:47:02',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'ইসমাইল ভ্যান',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:50:54',
                'updated_at' => '2023-12-21 07:50:54',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'ফোরকান ভ্যান',
                'address' => 'ফেনী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:51:21',
                'updated_at' => '2023-12-21 07:51:21',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'আযাদ ভাই',
                'address' => 'পাঠান বাড়ি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:51:57',
                'updated_at' => '2023-12-21 07:51:57',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'শাহীন হোটেল',
                'address' => 'হাসপাতাল মোড়',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 07:53:03',
                'updated_at' => '2023-12-21 07:53:03',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'কামাল বানিজ্যালয়',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:36:27',
                'updated_at' => '2023-12-21 10:36:27',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'বেলাল ভাই',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:38:12',
                'updated_at' => '2023-12-21 10:38:12',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'মদীনা বানিজ্যালয়',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:38:52',
                'updated_at' => '2023-12-21 10:38:52',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'মা-ট্রেডার্স',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:39:46',
                'updated_at' => '2023-12-21 10:39:46',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'নবী এন্টারপ্রাইজ',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:40:34',
                'updated_at' => '2023-12-21 10:40:34',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'আতিক এন্ড সন্স',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:41:04',
                'updated_at' => '2023-12-21 10:41:04',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'আলী হোসেন',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:41:48',
                'updated_at' => '2023-12-21 10:41:48',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'মহিনউদ্দিন ভাই',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:42:26',
                'updated_at' => '2023-12-21 10:42:26',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'অজি উল্ল্যাহ',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:43:03',
                'updated_at' => '2023-12-21 10:43:03',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'আমীর ষ্টোর',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:43:33',
                'updated_at' => '2023-12-21 10:43:33',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'হাবিব ভাই',
                'address' => 'বসুরহাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:44:11',
                'updated_at' => '2023-12-21 10:44:11',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'হাজী মোস্তফা',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:45:47',
                'updated_at' => '2023-12-21 10:45:47',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'হোসেন মিয়া',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:46:17',
                'updated_at' => '2023-12-21 10:46:17',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'ফরিদ আহম্মদ',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:46:48',
                'updated_at' => '2023-12-21 10:46:48',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'সরোয়ার মিয়া',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:47:46',
                'updated_at' => '2023-12-21 10:47:46',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'হেলাল ভাই',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:48:06',
                'updated_at' => '2023-12-21 10:48:06',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'সোহেল ষ্টোর',
                'address' => 'বাংলা বাজার',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:48:32',
                'updated_at' => '2023-12-21 10:48:32',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'জাকির ষ্টোর',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:49:23',
                'updated_at' => '2023-12-21 10:49:23',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'সোহাগ ভাই',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:49:52',
                'updated_at' => '2023-12-21 10:49:52',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'আবির ষ্টোর',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:50:27',
                'updated_at' => '2023-12-21 10:50:27',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'কুদ্দুস মিয়া',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:51:01',
                'updated_at' => '2023-12-21 10:51:01',
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'আলমগীর ষ্টোর',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:51:36',
                'updated_at' => '2023-12-21 10:51:36',
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'তাহের ষ্টোর',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:52:10',
                'updated_at' => '2023-12-21 10:52:10',
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'সবুজ মিয়া',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:52:30',
                'updated_at' => '2023-12-21 10:52:30',
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'ফয়সাল ভাই',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:52:55',
                'updated_at' => '2023-12-21 10:52:55',
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'আজিজ ভাই',
                'address' => 'পেশকার হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:53:18',
                'updated_at' => '2023-12-21 10:53:18',
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'হোসেন ভাই',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:54:48',
                'updated_at' => '2023-12-21 10:54:48',
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'সাহাব উদ্দিন',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:55:22',
                'updated_at' => '2023-12-21 10:55:22',
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'রহিম ভাই',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:55:46',
                'updated_at' => '2023-12-21 10:55:46',
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'সাইফুল ভাই',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:56:18',
                'updated_at' => '2023-12-21 10:57:06',
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'অমর বাবু',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:58:51',
                'updated_at' => '2023-12-21 10:58:51',
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'পরিমল বাবু',
                'address' => 'চাপরাশির হাট',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 10:59:13',
                'updated_at' => '2023-12-21 10:59:13',
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'মুজিব ভাই',
                'address' => 'তেমুহনী',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:00:03',
                'updated_at' => '2023-12-21 11:00:03',
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'মিলন ভাই',
                'address' => 'তেমুহনী',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:00:33',
                'updated_at' => '2023-12-21 11:00:33',
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'মক্কা ষ্টোর',
                'address' => 'তেমুহনী',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:00:56',
                'updated_at' => '2023-12-21 11:00:56',
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'সবুজ ভাই',
                'address' => 'তেমুহনী',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:01:20',
                'updated_at' => '2023-12-21 11:01:20',
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'সোনাপুর এগ্রোর',
                'address' => 'সিলোনিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:02:15',
                'updated_at' => '2023-12-21 11:02:15',
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'ইসমাইল ষ্টোর',
                'address' => 'সিলোনিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:02:45',
                'updated_at' => '2023-12-21 11:02:45',
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'মুন্সি মিয়া',
                'address' => 'সিলোনিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:03:57',
                'updated_at' => '2023-12-21 11:03:57',
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'ইসহাক ভাই',
                'address' => 'সিলোনিয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:04:36',
                'updated_at' => '2023-12-21 11:04:36',
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'শামছু মিয়া',
                'address' => 'জায়লস্কর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:06:10',
                'updated_at' => '2023-12-21 11:06:10',
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'সবুজ মিয়া',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:06:39',
                'updated_at' => '2023-12-21 11:06:39',
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'রুবেল মিয়া',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:06:58',
                'updated_at' => '2023-12-21 11:06:58',
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'শফী কাকা',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:07:20',
                'updated_at' => '2023-12-21 11:07:20',
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'জাফর ভাই',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:07:41',
                'updated_at' => '2023-12-21 11:07:41',
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'জাব্বার মিয়া',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:07:58',
                'updated_at' => '2023-12-21 11:07:58',
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'হোসেন ভাই',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:08:18',
                'updated_at' => '2023-12-21 11:08:18',
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'বাবুল ভাই',
                'address' => 'বেকের বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:08:34',
                'updated_at' => '2023-12-21 11:08:34',
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'আব্দুল হক ট্রেডার্স',
                'address' => 'দাগন ভুঁইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:09:14',
                'updated_at' => '2023-12-21 11:09:47',
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'কামাল ব্রাদার্স',
                'address' => 'দাগন ভুঁইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:10:23',
                'updated_at' => '2023-12-21 11:10:23',
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'কবির মিয়া',
                'address' => 'দাগন ভুঁইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:10:54',
                'updated_at' => '2023-12-21 11:10:54',
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'হাসান ভাই',
                'address' => 'কোরশ মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:11:55',
                'updated_at' => '2023-12-21 11:11:55',
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'মোল্লা কামাল',
                'address' => 'কোরশ মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:12:19',
                'updated_at' => '2023-12-21 11:12:19',
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'নজরুল ভাই',
                'address' => 'কোরশ মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:12:40',
                'updated_at' => '2023-12-21 11:12:40',
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'তমিজ মিয়া',
                'address' => 'কোরশ মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:13:25',
                'updated_at' => '2023-12-21 11:13:25',
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'সিকদার পরিবহন',
                'address' => 'গুনবতী',
                'mobile' => '00',
                'area' => 'কুমিল্লা',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:14:20',
                'updated_at' => '2023-12-21 11:14:20',
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'দুলাল মিয়া',
                'address' => 'গুনবতী',
                'mobile' => '00',
                'area' => 'কুমিল্লা',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:14:58',
                'updated_at' => '2023-12-21 11:14:58',
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'সেলিম মিয়া',
                'address' => 'গুনবতী',
                'mobile' => '00',
                'area' => 'কুমিল্লা',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:15:23',
                'updated_at' => '2023-12-21 11:15:23',
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'ব্রাদার্স ষ্টোর',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:17:21',
                'updated_at' => '2023-12-21 11:17:21',
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'নুর নবী',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:18:00',
                'updated_at' => '2023-12-21 11:18:00',
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'এমরান ভাই',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:18:41',
                'updated_at' => '2023-12-21 11:18:41',
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'মানিক ভাই',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:19:28',
                'updated_at' => '2023-12-21 11:19:28',
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'হাবিব ভাই',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:19:54',
                'updated_at' => '2023-12-21 11:19:54',
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'এমরান ড্রাইভার',
                'address' => 'মোহাম্মদ আলী বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:20:50',
                'updated_at' => '2023-12-21 11:20:50',
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'আরিফ ভাই',
                'address' => 'এলাহিগঞ্জ',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:21:33',
                'updated_at' => '2023-12-21 11:21:33',
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'মিলন ষ্টোর',
                'address' => 'এলাহিগঞ্জ',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:22:02',
                'updated_at' => '2023-12-21 11:22:02',
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'আরিফ ভাই',
                'address' => 'সিন্দুরপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:22:34',
                'updated_at' => '2023-12-21 11:22:34',
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'বিসমিল্লাহ ষ্টোর',
                'address' => 'সিন্দুরপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:23:51',
                'updated_at' => '2023-12-21 11:23:51',
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'আবুল কাশেম',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:24:26',
                'updated_at' => '2023-12-21 11:24:26',
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'মানিক ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:25:01',
                'updated_at' => '2023-12-21 11:25:01',
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'সোহেল ষ্টোর',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:25:23',
                'updated_at' => '2023-12-21 11:25:23',
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'মোজাহের ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:25:48',
                'updated_at' => '2023-12-21 11:25:48',
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'বাহার ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:26:07',
                'updated_at' => '2023-12-21 11:26:07',
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'জামাল ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:26:41',
                'updated_at' => '2023-12-21 11:26:41',
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'কাইয়ুম মিয়া',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:27:49',
                'updated_at' => '2023-12-21 11:27:49',
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'নেজাম ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:28:08',
                'updated_at' => '2023-12-21 11:28:08',
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'খায়ের মিয়া',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:28:49',
                'updated_at' => '2023-12-21 11:28:49',
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'রুস্তম ষ্টোর',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:29:13',
                'updated_at' => '2023-12-21 11:29:13',
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'আউয়াল ভাই',
                'address' => 'রাজাপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:30:25',
                'updated_at' => '2023-12-21 11:30:25',
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'ইউনুস ভাই',
                'address' => 'শর্শদী',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:31:16',
                'updated_at' => '2023-12-21 11:31:16',
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'মানিক বাবু',
                'address' => 'মুন্সিরহাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:32:02',
                'updated_at' => '2023-12-21 11:32:02',
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'মুছা ভাই',
                'address' => 'মুন্সিরহাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:32:34',
                'updated_at' => '2023-12-21 11:32:34',
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'সাধন দা',
                'address' => 'মুন্সিরহাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:33:00',
                'updated_at' => '2023-12-21 11:33:00',
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'হান্নান ভাই',
                'address' => 'মুন্সিরহাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:33:22',
                'updated_at' => '2023-12-21 11:33:22',
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'মাধব সাহা',
                'address' => 'পরশুরাম',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:34:05',
                'updated_at' => '2023-12-21 11:34:05',
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'মা-বাবা ষ্টোর',
                'address' => 'পরশুরাম',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:34:41',
                'updated_at' => '2023-12-21 11:34:41',
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'ত্রিমল হাজারী',
                'address' => 'পরশুরাম',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:35:05',
                'updated_at' => '2023-12-21 11:35:05',
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'ইসমাইল ভাই',
                'address' => 'পরশুরাম',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:35:49',
                'updated_at' => '2023-12-21 11:35:49',
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'মিয়া সওদাগর',
                'address' => 'ছাগলনাইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:36:45',
                'updated_at' => '2023-12-21 11:36:45',
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'মিনার মিয়া',
                'address' => 'ছাগলনাইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:37:21',
                'updated_at' => '2023-12-21 11:37:21',
            ),
            176 => 
            array (
                'id' => 177,
                'name' => 'রহিম টি',
                'address' => 'ছাগলনাইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:37:50',
                'updated_at' => '2023-12-21 11:37:50',
            ),
            177 => 
            array (
                'id' => 178,
                'name' => 'হারাধন বনিক',
                'address' => 'ছাগলনাইয়া',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:38:41',
                'updated_at' => '2023-12-21 11:38:41',
            ),
            178 => 
            array (
                'id' => 179,
                'name' => 'জসীম ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:40:05',
                'updated_at' => '2023-12-21 11:40:05',
            ),
            179 => 
            array (
                'id' => 180,
                'name' => 'আব্দুল কালাম',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:40:35',
                'updated_at' => '2023-12-21 11:40:35',
            ),
            180 => 
            array (
                'id' => 181,
                'name' => 'বাপ্পী ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:41:02',
                'updated_at' => '2023-12-21 11:41:02',
            ),
            181 => 
            array (
                'id' => 182,
                'name' => 'দিদার ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:41:30',
                'updated_at' => '2023-12-21 11:41:30',
            ),
            182 => 
            array (
                'id' => 183,
                'name' => 'নিমীহ বাবু',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:42:03',
                'updated_at' => '2023-12-21 11:42:03',
            ),
            183 => 
            array (
                'id' => 184,
                'name' => 'দেলোয়ার ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:42:32',
                'updated_at' => '2023-12-21 11:42:32',
            ),
            184 => 
            array (
                'id' => 185,
                'name' => 'আলী আকবর',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:43:32',
                'updated_at' => '2023-12-21 11:43:32',
            ),
            185 => 
            array (
                'id' => 186,
                'name' => 'শাকিল ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:44:08',
                'updated_at' => '2023-12-21 11:44:08',
            ),
            186 => 
            array (
                'id' => 187,
                'name' => 'গিয়াস উদ্দিন',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:44:32',
                'updated_at' => '2023-12-21 11:44:32',
            ),
            187 => 
            array (
                'id' => 188,
                'name' => 'শাহ আলম ভাই',
                'address' => 'বড় দারোগার হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:45:06',
                'updated_at' => '2023-12-21 11:45:06',
            ),
            188 => 
            array (
                'id' => 189,
                'name' => 'শাহজাহান ভাই',
                'address' => 'কে এম হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:47:06',
                'updated_at' => '2023-12-21 11:47:06',
            ),
            189 => 
            array (
                'id' => 190,
                'name' => 'মামুন ভাই',
                'address' => 'কাজীর হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:47:49',
                'updated_at' => '2023-12-21 11:47:49',
            ),
            190 => 
            array (
                'id' => 191,
                'name' => 'ছালাম ভাই',
                'address' => 'কাজীর হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:49:31',
                'updated_at' => '2023-12-21 11:49:31',
            ),
            191 => 
            array (
                'id' => 192,
                'name' => 'আব্দুর রব',
                'address' => 'কাজীর হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:50:43',
                'updated_at' => '2023-12-21 11:50:43',
            ),
            192 => 
            array (
                'id' => 193,
                'name' => 'রমিজ ভাই',
                'address' => 'গুইমারা',
                'mobile' => '00',
                'area' => 'খাগড়াছড়ি',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:52:02',
                'updated_at' => '2023-12-21 11:52:02',
            ),
            193 => 
            array (
                'id' => 194,
                'name' => 'ইলিয়াছ ভাই',
                'address' => 'হাদী ফকির হাট',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:53:07',
                'updated_at' => '2023-12-21 11:53:07',
            ),
            194 => 
            array (
                'id' => 195,
                'name' => 'নবী ভাই',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:53:37',
                'updated_at' => '2023-12-21 11:53:37',
            ),
            195 => 
            array (
                'id' => 196,
                'name' => 'নিতীহ সাহা',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:54:11',
                'updated_at' => '2023-12-21 11:54:11',
            ),
            196 => 
            array (
                'id' => 197,
                'name' => 'হাদী ভাই',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:55:16',
                'updated_at' => '2023-12-21 11:55:16',
            ),
            197 => 
            array (
                'id' => 198,
                'name' => 'মিজান ভাই',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:56:10',
                'updated_at' => '2023-12-21 11:56:10',
            ),
            198 => 
            array (
                'id' => 199,
                'name' => 'নেয়াজ ভাই',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:56:54',
                'updated_at' => '2023-12-21 11:56:54',
            ),
            199 => 
            array (
                'id' => 200,
                'name' => 'মোহাম্মদ উল্ল্যাহ',
                'address' => 'বক্তার মুন্সি',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:57:17',
                'updated_at' => '2023-12-21 11:57:17',
            ),
            200 => 
            array (
                'id' => 201,
                'name' => 'ওহাব ষ্টোর',
                'address' => 'আমজাদ হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:58:00',
                'updated_at' => '2023-12-21 11:58:00',
            ),
            201 => 
            array (
                'id' => 202,
                'name' => 'মোতালেব ভাই',
                'address' => 'বিরুলী',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:58:58',
                'updated_at' => '2023-12-21 11:58:58',
            ),
            202 => 
            array (
                'id' => 203,
                'name' => 'নবেল মিয়া',
                'address' => 'বিরুলী',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:59:28',
                'updated_at' => '2023-12-21 11:59:28',
            ),
            203 => 
            array (
                'id' => 204,
                'name' => 'সিরাজ মিয়া',
                'address' => 'কালামুন্সি',
                'mobile' => '00',
                'area' => 'নোয়াখালী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 11:59:59',
                'updated_at' => '2023-12-21 11:59:59',
            ),
            204 => 
            array (
                'id' => 205,
                'name' => 'আব্দুল হাই',
                'address' => 'আমিন বাজার',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:00:32',
                'updated_at' => '2023-12-21 12:00:32',
            ),
            205 => 
            array (
                'id' => 206,
                'name' => 'ফারহানা ষ্টোর',
                'address' => 'জি এম হাট',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:01:08',
                'updated_at' => '2023-12-21 12:01:08',
            ),
            206 => 
            array (
                'id' => 207,
                'name' => 'মহীউদ্দিন মিয়া',
                'address' => 'মিঠাছড়া',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:01:52',
                'updated_at' => '2023-12-21 12:01:52',
            ),
            207 => 
            array (
                'id' => 208,
                'name' => 'বাদশা মিয়া',
                'address' => 'মিঠাছড়া',
                'mobile' => '00',
                'area' => 'চট্টগ্রাম',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:02:12',
                'updated_at' => '2023-12-21 12:02:12',
            ),
            208 => 
            array (
                'id' => 209,
                'name' => 'জামাল ভাই',
                'address' => 'শিবপুর',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:03:15',
                'updated_at' => '2023-12-21 12:03:15',
            ),
            209 => 
            array (
                'id' => 210,
                'name' => 'মালেশিয়া হোটেল',
                'address' => 'কাজীর বাগ',
                'mobile' => '00',
                'area' => 'ফেনী',
                'old_amount' => 0.0,
                'status' => 1,
                'created_at' => '2023-12-21 12:05:19',
                'updated_at' => '2023-12-21 12:05:19',
            ),
        ));
        
        
    }
}