<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PonnoPurchaseEntriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ponno_purchase_entries')->delete();
        
        \DB::table('ponno_purchase_entries')->insert(array (
            0 => 
            array (
                'id' => 1001,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 1,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 3,
                'weight' => 135.0,
                'rate' => 105.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 11:21:48',
                'updated_at' => '2024-01-05 12:58:20',
            ),
            1 => 
            array (
                'id' => 1002,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 1,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 45,
                'weight' => 2025.0,
                'rate' => 120.0,
                'labour_cost' => 250.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 11:23:42',
                'updated_at' => '2024-01-05 12:58:06',
            ),
            2 => 
            array (
                'id' => 1003,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 940.0,
                'rate' => 82.0,
                'labour_cost' => 200.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 11:25:33',
                'updated_at' => '2024-01-05 12:57:54',
            ),
            3 => 
            array (
                'id' => 1004,
                'purchase_type' => 2,
                'mohajon_setup_id' => 30,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 22,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 550.0,
                'other_cost' => 0.0,
                'truck_cost' => 10000.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:43:28',
                'updated_at' => '2024-01-05 12:57:45',
            ),
            4 => 
            array (
                'id' => 1005,
                'purchase_type' => 2,
                'mohajon_setup_id' => 23,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 15,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 120.0,
                'other_cost' => 0.0,
                'truck_cost' => 1500.0,
                'van_cost' => 200.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.0,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:47:26',
                'updated_at' => '2024-01-09 11:56:07',
            ),
            5 => 
            array (
                'id' => 1006,
                'purchase_type' => 2,
                'mohajon_setup_id' => 30,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 15,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 120.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 225.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.0,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:49:06',
                'updated_at' => '2024-01-06 15:44:45',
            ),
            6 => 
            array (
                'id' => 1007,
                'purchase_type' => 2,
                'mohajon_setup_id' => 30,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 15,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 120.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.0,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:49:56',
                'updated_at' => '2024-01-09 10:26:17',
            ),
            7 => 
            array (
                'id' => 1008,
                'purchase_type' => 2,
                'mohajon_setup_id' => 33,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 252,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 976.0,
                'other_cost' => 0.0,
                'truck_cost' => 32000.0,
                'van_cost' => 500.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.0,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:52:03',
                'updated_at' => '2024-01-08 07:10:51',
            ),
            8 => 
            array (
                'id' => 1009,
                'purchase_type' => 2,
                'mohajon_setup_id' => 18,
                'ponno_setup_id' => 1,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:52:50',
                'updated_at' => '2024-01-05 12:56:49',
            ),
            9 => 
            array (
                'id' => 1010,
                'purchase_type' => 2,
                'mohajon_setup_id' => 26,
                'ponno_setup_id' => 8,
                'size_id' => 5,
                'marka_id' => 2,
                'gari_no' => '0',
                'quantity' => 10,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 50.0,
                'other_cost' => 0.0,
                'truck_cost' => 500.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:57:57',
                'updated_at' => '2024-01-05 12:56:40',
            ),
            10 => 
            array (
                'id' => 1011,
                'purchase_type' => 2,
                'mohajon_setup_id' => 27,
                'ponno_setup_id' => 8,
                'size_id' => 5,
                'marka_id' => 3,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 100.0,
                'other_cost' => 0.0,
                'truck_cost' => 1000.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 12:59:27',
                'updated_at' => '2024-01-05 12:56:30',
            ),
            11 => 
            array (
                'id' => 1012,
                'purchase_type' => 2,
                'mohajon_setup_id' => 35,
                'ponno_setup_id' => 16,
                'size_id' => 5,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 400.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:02:44',
                'updated_at' => '2024-01-05 12:56:21',
            ),
            12 => 
            array (
                'id' => 1013,
                'purchase_type' => 2,
                'mohajon_setup_id' => 25,
                'ponno_setup_id' => 16,
                'size_id' => 5,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 7,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 70.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:03:35',
                'updated_at' => '2024-01-05 12:56:10',
            ),
            13 => 
            array (
                'id' => 1014,
                'purchase_type' => 1,
                'mohajon_setup_id' => 38,
                'ponno_setup_id' => 31,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 1362.0,
                'rate' => 56.5,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:18:03',
                'updated_at' => '2024-01-05 12:55:58',
            ),
            14 => 
            array (
                'id' => 1015,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 31,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 290.0,
                'rate' => 55.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:19:39',
                'updated_at' => '2024-01-05 12:55:44',
            ),
            15 => 
            array (
                'id' => 1016,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 31,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 4,
                'weight' => 230.0,
                'rate' => 49.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:28:11',
                'updated_at' => '2024-01-05 12:55:27',
            ),
            16 => 
            array (
                'id' => 1017,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 7,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 100.0,
                'rate' => 210.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:30:50',
                'updated_at' => '2024-01-05 12:55:15',
            ),
            17 => 
            array (
                'id' => 1018,
                'purchase_type' => 1,
                'mohajon_setup_id' => 34,
                'ponno_setup_id' => 7,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 2,
                'weight' => 40.0,
                'rate' => 190.0,
                'labour_cost' => 10.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-01',
                'created_at' => '2024-01-01 13:33:48',
                'updated_at' => '2024-01-05 12:55:00',
            ),
            18 => 
            array (
                'id' => 1019,
                'purchase_type' => 1,
                'mohajon_setup_id' => 4,
                'ponno_setup_id' => 7,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 1,
                'weight' => 20.0,
                'rate' => 205.0,
                'labour_cost' => 5.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 09:38:29',
                'updated_at' => '2024-01-05 12:54:43',
            ),
            19 => 
            array (
                'id' => 1020,
                'purchase_type' => 1,
                'mohajon_setup_id' => 7,
                'ponno_setup_id' => 7,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 15,
                'weight' => 300.0,
                'rate' => 193.0,
                'labour_cost' => 75.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 11:36:13',
                'updated_at' => '2024-01-05 12:54:34',
            ),
            20 => 
            array (
                'id' => 1021,
                'purchase_type' => 1,
                'mohajon_setup_id' => 9,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 1222.0,
                'rate' => 46.5,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 11:43:51',
                'updated_at' => '2024-01-05 12:54:25',
            ),
            21 => 
            array (
                'id' => 1022,
                'purchase_type' => 2,
                'mohajon_setup_id' => 30,
                'ponno_setup_id' => 2,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 16,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 128.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 11:49:47',
                'updated_at' => '2024-01-05 12:54:01',
            ),
            22 => 
            array (
                'id' => 1023,
                'purchase_type' => 2,
                'mohajon_setup_id' => 23,
                'ponno_setup_id' => 2,
                'size_id' => 4,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 10,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 80.0,
                'other_cost' => 0.0,
                'truck_cost' => 850.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.0,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 11:51:51',
                'updated_at' => '2024-01-09 12:20:11',
            ),
            23 => 
            array (
                'id' => 1024,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 6,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 1,
                'weight' => 53.0,
                'rate' => 54.0,
                'labour_cost' => 15.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 11:59:10',
                'updated_at' => '2024-01-05 12:53:25',
            ),
            24 => 
            array (
                'id' => 1025,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 1,
                'weight' => 67.0,
                'rate' => 49.25,
                'labour_cost' => 15.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 12:02:24',
                'updated_at' => '2024-01-05 12:53:11',
            ),
            25 => 
            array (
                'id' => 1026,
                'purchase_type' => 1,
                'mohajon_setup_id' => 36,
                'ponno_setup_id' => 10,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 100.0,
                'rate' => 173.0,
                'labour_cost' => 25.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-02 12:44:16',
                'updated_at' => '2024-01-05 12:52:55',
            ),
            26 => 
            array (
                'id' => 1027,
                'purchase_type' => 2,
                'mohajon_setup_id' => 37,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 19,
                'weight' => 781.5,
                'rate' => NULL,
                'labour_cost' => 160.0,
                'other_cost' => 0.0,
                'truck_cost' => 1690.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2023-12-25',
                'created_at' => '2024-01-02 14:54:00',
                'updated_at' => '2024-01-05 12:52:41',
            ),
            27 => 
            array (
                'id' => 1028,
                'purchase_type' => 1,
                'mohajon_setup_id' => 9,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 1,
                'weight' => 60.0,
                'rate' => 50.0,
                'labour_cost' => 15.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-02',
                'created_at' => '2024-01-03 07:35:14',
                'updated_at' => '2024-01-05 12:52:26',
            ),
            28 => 
            array (
                'id' => 1030,
                'purchase_type' => 1,
                'mohajon_setup_id' => 7,
                'ponno_setup_id' => 7,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 30,
                'weight' => 600.0,
                'rate' => 194.0,
                'labour_cost' => 150.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:26:32',
                'updated_at' => '2024-01-05 12:51:57',
            ),
            29 => 
            array (
                'id' => 1031,
                'purchase_type' => 1,
                'mohajon_setup_id' => 4,
                'ponno_setup_id' => 7,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 400.0,
                'rate' => 193.0,
                'labour_cost' => 100.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:27:25',
                'updated_at' => '2024-01-05 12:51:49',
            ),
            30 => 
            array (
                'id' => 1032,
                'purchase_type' => 1,
                'mohajon_setup_id' => 6,
                'ponno_setup_id' => 2,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 946.0,
                'rate' => 86.0,
                'labour_cost' => 200.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:28:21',
                'updated_at' => '2024-01-05 12:51:41',
            ),
            31 => 
            array (
                'id' => 1033,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 6,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 300.0,
                'rate' => 52.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:29:10',
                'updated_at' => '2024-01-05 12:51:28',
            ),
            32 => 
            array (
                'id' => 1034,
                'purchase_type' => 1,
                'mohajon_setup_id' => 9,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 1201.0,
                'rate' => 46.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:29:51',
                'updated_at' => '2024-01-05 12:51:21',
            ),
            33 => 
            array (
                'id' => 1035,
                'purchase_type' => 1,
                'mohajon_setup_id' => 9,
                'ponno_setup_id' => 31,
                'size_id' => 6,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 285.0,
                'rate' => 53.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:30:29',
                'updated_at' => '2024-01-05 12:51:13',
            ),
            34 => 
            array (
                'id' => 1036,
                'purchase_type' => 1,
                'mohajon_setup_id' => 3,
                'ponno_setup_id' => 10,
                'size_id' => 1,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 5,
                'weight' => 100.0,
                'rate' => 168.0,
                'labour_cost' => 25.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 1.5,
                'entry_date' => '2024-01-03',
                'created_at' => '2024-01-03 11:31:10',
                'updated_at' => '2024-01-05 12:51:05',
            ),
            35 => 
            array (
                'id' => 1037,
                'purchase_type' => 2,
                'mohajon_setup_id' => 23,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 160.0,
                'other_cost' => 0.0,
                'truck_cost' => 400.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-04',
                'created_at' => '2024-01-04 09:08:43',
                'updated_at' => '2024-01-05 12:50:55',
            ),
            36 => 
            array (
                'id' => 1038,
                'purchase_type' => 2,
                'mohajon_setup_id' => 30,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 16,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 128.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-04',
                'created_at' => '2024-01-04 09:17:51',
                'updated_at' => '2024-01-05 12:50:45',
            ),
            37 => 
            array (
                'id' => 1039,
                'purchase_type' => 2,
                'mohajon_setup_id' => 25,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 10,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 80.0,
                'other_cost' => 0.0,
                'truck_cost' => 630.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-04',
                'created_at' => '2024-01-04 13:14:14',
                'updated_at' => '2024-01-05 12:50:39',
            ),
            38 => 
            array (
                'id' => 1040,
                'purchase_type' => 2,
                'mohajon_setup_id' => 25,
                'ponno_setup_id' => 2,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 10,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 80.0,
                'other_cost' => 0.0,
                'truck_cost' => 820.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-08',
                'created_at' => '2024-01-08 09:59:52',
                'updated_at' => '2024-01-08 09:59:52',
            ),
            39 => 
            array (
                'id' => 1041,
                'purchase_type' => 2,
                'mohajon_setup_id' => 39,
                'ponno_setup_id' => 1,
                'size_id' => 3,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 0.0,
                'rate' => NULL,
                'labour_cost' => 160.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-08',
                'created_at' => '2024-01-08 10:08:24',
                'updated_at' => '2024-01-08 10:08:24',
            ),
            40 => 
            array (
                'id' => 1042,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 1,
                'weight' => 65.0,
                'rate' => 45.0,
                'labour_cost' => 15.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-08',
                'created_at' => '2024-01-08 10:12:00',
                'updated_at' => '2024-01-08 13:27:07',
            ),
            41 => 
            array (
                'id' => 1043,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 7,
                'weight' => 502.0,
                'rate' => 45.0,
                'labour_cost' => 105.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-08',
                'created_at' => '2024-01-08 12:28:58',
                'updated_at' => '2024-01-08 13:37:14',
            ),
            42 => 
            array (
                'id' => 1044,
                'purchase_type' => 1,
                'mohajon_setup_id' => 10,
                'ponno_setup_id' => 31,
                'size_id' => 6,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 20,
                'weight' => 1257.0,
                'rate' => 49.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-09',
                'created_at' => '2024-01-09 13:25:05',
                'updated_at' => '2024-01-09 17:38:53',
            ),
            43 => 
            array (
                'id' => 1045,
                'purchase_type' => 1,
                'mohajon_setup_id' => 9,
                'ponno_setup_id' => 31,
                'size_id' => 7,
                'marka_id' => 1,
                'gari_no' => '0',
                'quantity' => 10,
                'weight' => 581.0,
                'rate' => 42.0,
                'labour_cost' => 0.0,
                'other_cost' => 0.0,
                'truck_cost' => 0.0,
                'van_cost' => 0.0,
                'tohori_cost' => 0.0,
                'mohajon_commission' => 0.7,
                'entry_date' => '2024-01-09',
                'created_at' => '2024-01-09 13:26:06',
                'updated_at' => '2024-01-09 17:37:51',
            ),
        ));
        
        
    }
}